### ISSUE TITLE
DEMP2 alt fire shell broken currently / implement RF_VOLUMETRIC.

### ISSUE THREAD

**Issue by ensiform** [xycaleth/OpenJK#39]
See 
![shot2016-04-23_14-02-00](https://cloud.githubusercontent.com/assets/997399/14763492/7a6d19d4-095c-11e6-81f8-a2cec8d5fd15.png)

If you need my config or gfx etc ill look later if this doesn't happen for you.

**Comment by xycaleth** [comment]
Potentially an issue with the basejka shader:
```
gfx/effects/demp2shell
{
	cull	twosided
    {
        map gfx/effects/plasma
        blendFunc GL_ONE GL_ONE
        glow
        rgbGen vertex
        tcMod scale 2 3
        tcMod scroll 1 0.5
    }
    {
        map gfx/effects/plasma
        blendFunc GL_ONE GL_ONE
        rgbGen vertex
        tcMod scale 3 2
        tcMod scroll 0.5 2.6
    }
}
```

Here's it's using `rgbGen vertex` which means to modulate the color with the vertex lighting, from the map. However, cgame is trying to fade out the explosion using the `shaderRGBA` variable.

**Comment by xycaleth** [comment]
It looks like the vanilla renderer adds some extra code to make use of `shaderRGBA` when the ref entity is flagged with `RF_VOLUMETRIC`:

https://github.com/xycaleth/OpenJK/blob/master/codemp/rd-vanilla/tr_shade.cpp#L1161-L1188

This code is missing from rend2.

**Comment by ensiform** [comment]
Were you able to figure out why the map geometry for the big bacta tank also has the similar issue?

**Comment by xycaleth** [comment]
Not yet. I'm thinking different issue.

**Comment by xycaleth** [comment]
Fixed in db57b4f.

**Comment by ensiform** [comment]
It still appears sometimes for a frame at the very end of the shell.

**Comment by ensiform** [comment]
[![Video of Bug still happening for reference](http://img.youtube.com/vi/jTp-hxmusRY/0.jpg)](https://youtu.be/jTp-hxmusRY)

**Comment by xycaleth** [comment]
Possibly fixed in b13418e?

**Comment by xycaleth** [comment]
Confirmed to be fixed by @ensiform.
